# Generated by Django 2.2.9 on 2020-01-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
