# Generated by Django 2.2.9 on 2020-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='store_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='店名'),
        ),
    ]
